Repository rishabh-jain424/open-source-applications-or-tools, pull requests merged in 2020-10, with the labels that each got.

#1 Add categories & tools
  README.md
Labels: good first issue, hacktoberfest-accepted, 🔍 Ready for Review

#2 Update README.md
  README.md
Labels: hacktoberfest-accepted, 🔍 Ready for Review

#4 Add CONTRIBUTORS
  CONTRIBUTORS.md
  README.md
Labels: documentation, hacktoberfest-accepted, 🔍 Ready for Review

#5 added some opensource applications
  README.md
Labels: hacktoberfest-accepted, 🔍 Ready for Review

#9 Update index.md
  index.md
Labels: hacktoberfest-accepted, 🔍 Ready for Review

#14 adding frameworks/libs
  README.md
  index.md
Labels: hacktoberfest-accepted, hacktoberfest2020, 🔍 Ready for Review

#16 Added IDE & Coding Editor names.
  README.md
  index.md
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2020, 🔍 Ready for Review

#18 Added Voice, ML & Data science tools.
  index.md
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2020, ✅ Approved, 🔍 Ready for Review

#19 Added mobile development, editor, bots and voice app
  index.md
Labels: hacktoberfest-accepted, hacktoberfest2020, ✅ Approved, 🔍 Ready for Review
